version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: highload-nginx
        volumes:
            - .:/app
            - ./dev-tools/docker/local/nginx:/etc/nginx/conf.d
        command: nginx -g 'daemon off;'
        networks:
            highload-network:
                ipv4_address: 192.168.111.10
        depends_on:
            - php

    php:
        container_name: highload-php
        build: dev-tools/docker/local/php
        volumes:
            - .:/var/www/highload
            - ./dev-tools/docker/local/php/php.ini:/etc/php/7.4/cli/php.ini
        command: php-fpm7.4 -F
        environment:
            USER_ID: ${DOCKER_USER_ID}
        depends_on:
            - maria-db-master
            - maria-db-slave
        networks:
            highload-network:
                ipv4_address: 192.168.111.20

    maria-db-master:
        image: mariadb
        container_name: ${DOCKER_DB_MASTER_HOST}
        volumes:
            - ./dumps:/dumps
            - ./databases/maria-master:/var/lib/mysql
            - ./dev-tools/docker/local/mariadb-master/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        environment:
            MYSQL_ROOT_PASSWORD: 123
        networks:
            highload-network:
                ipv4_address: 192.168.111.31

    maria-db-slave:
        image: mariadb
        container_name: ${DOCKER_DB_SLAVE_HOST}
        volumes:
            - ./dumps:/dumps
            - ./databases/maria-slave:/var/lib/mysql
            - ./dev-tools/docker/local/mariadb-slave/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        environment:
            MYSQL_ROOT_PASSWORD: 123
        networks:
            highload-network:
                ipv4_address: 192.168.111.32

networks:
    highload-network:
        ipam:
            config:
                - subnet: 192.168.111.0/24
